// LOCALHOST 
### Get all users
GET http://localhost:8080/user
### Get user by id
GET http://localhost:8080/user/63cb1e726e537ba438601dba
### Get user by id
GET http://localhost:8080/contacts/63cb1e726e537ba438601dbb


### Create user
POST http://localhost:8080/user HTTP/1.1
Content-Type: application/json

{

}

### Put contact
PUT http://localhost:8080/contacts/63c4ec75286d658825f01186 HTTP/1.1
Content-Type: application/json

{
    "username":"Ashley",
    "password":"Weaver",
    "email":"ashleyW@test.com",
    "phoneNumber":"985642117",
    "onlineStudent":"false",
    "campusStudent":"true",
    "semester": "fall",
    "theme_name": "dark theme"
}


### Delete contact
DELETE http://localhost:8080/user/63c4ec75286d658825f01186 HTTP/1.1



// PRODUCTION Deploy ### GET all contacts

### Get all contacts
GET https://cse341-g3nr.onrender.com/contacts
### Get contact by id
GET https://cse341-g3nr.onrender.com/contacts/63c1edc902c351525efb64d7
### Get contact by id
GET https://cse341-g3nr.onrender.com/contacts/63c1edc902c351525efb64d8
### Get contact by id
GET https://cse341-g3nr.onrender.com/contacts/63c1edc902c351525efb64d9

### Create contact 
POST  https://cse341-g3nr.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}

### Put contact
PUT  https://cse341-g3nr.onrender.com/contacts/63c1edc902c351525efb64d9 HTTP/1.1
Content-Type: application/json

{
    "firstName":"Cristian",
    "lastName":"Cotrina",
    "email":"cris.cotrina@test.com",
    "favoriteColor":"Black",
    "birthday":"07/12/20"
}

### Delete contact
DELETE http://localhost:8080/contacts/63c4f2ee3a34cd81935741f4 HTTP/1.1